"""empty message

Revision ID: e87edc5ca496
Revises: 
Create Date: 2020-06-17 16:02:03.256089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87edc5ca496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('berita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=120), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('dokumen', sa.LargeBinary(length=8056), nullable=True),
    sa.Column('nama_dokumen', sa.String(length=124), nullable=True),
    sa.Column('gambar', sa.LargeBinary(length=4028), nullable=True),
    sa.Column('nama_gambar', sa.String(length=124), nullable=True),
    sa.Column('waktu_upload', sa.DateTime(), nullable=True),
    sa.Column('tampilkan', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_berita_waktu_upload'), 'berita', ['waktu_upload'], unique=False)
    op.create_table('data_sekolah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=60), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('nama_dokumen', sa.String(length=120), nullable=True),
    sa.Column('dokumen', sa.LargeBinary(length=8056), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('waktu_upload', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judul'),
    sa.UniqueConstraint('nama_dokumen'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_data_sekolah_waktu_upload'), 'data_sekolah', ['waktu_upload'], unique=False)
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruang', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruang')
    )
    op.create_table('prestasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=64), nullable=True),
    sa.Column('kategori', sa.String(length=24), nullable=True),
    sa.Column('tahun', sa.String(length=24), nullable=True),
    sa.Column('juara', sa.String(length=24), nullable=True),
    sa.Column('tingkat', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profil_sekolah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lembaga', sa.String(length=120), nullable=False),
    sa.Column('kode_pos', sa.String(length=10), nullable=False),
    sa.Column('kelurahan', sa.String(length=60), nullable=False),
    sa.Column('kecamatan', sa.String(length=60), nullable=False),
    sa.Column('kabupaten', sa.String(length=60), nullable=False),
    sa.Column('provinsi', sa.String(length=60), nullable=False),
    sa.Column('no_statistik', sa.String(length=60), nullable=False),
    sa.Column('akte_notaris', sa.String(length=60), nullable=False),
    sa.Column('kegiatan_belajar', sa.String(length=20), nullable=False),
    sa.Column('tahun_berdiri', sa.String(length=10), nullable=False),
    sa.Column('status_tk', sa.String(length=10), nullable=False),
    sa.Column('no_izin_pendirian', sa.String(length=46), nullable=False),
    sa.Column('no_izin_operasional', sa.String(length=46), nullable=False),
    sa.Column('kurikulum', sa.String(length=10), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('no_telepon', sa.String(length=13), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('visi_misi', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('elearning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dokumen', sa.LargeBinary(length=8056), nullable=True),
    sa.Column('nama_dokumen', sa.String(length=120), nullable=True),
    sa.Column('waktu_upload', sa.DateTime(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('judul', sa.String(length=120), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_dokumen'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_elearning_waktu_upload'), 'elearning', ['waktu_upload'], unique=False)
    op.create_table('jadwal_kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mata_pelajaran', sa.String(length=64), nullable=False),
    sa.Column('jam', sa.String(length=10), nullable=False),
    sa.Column('jam_end', sa.String(length=10), nullable=False),
    sa.Column('hari', sa.Enum('Senin', 'Selasa', 'Rabu', 'Kamis', "Jum'at", 'Sabtu', name='hari'), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('guru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=64), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('nik', sa.String(length=24), nullable=True),
    sa.Column('kelurahan', sa.String(length=24), nullable=True),
    sa.Column('kecamatan', sa.String(length=24), nullable=True),
    sa.Column('kabupaten', sa.String(length=24), nullable=True),
    sa.Column('provinsi', sa.String(length=24), nullable=True),
    sa.Column('agama', sa.Enum('Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Kong Hu Cu', name='agama'), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=24), nullable=True),
    sa.Column('tanggal_lahir', sa.String(length=24), nullable=True),
    sa.Column('jabatan', sa.Enum('Kepala Sekolah', 'Guru', name='jabatan'), nullable=True),
    sa.Column('foto', sa.LargeBinary(length=4028), nullable=True),
    sa.Column('nama_foto', sa.String(length=64), nullable=True),
    sa.Column('foto_ijazah', sa.LargeBinary(length=4028), nullable=True),
    sa.Column('nama_foto_ijazah', sa.String(length=64), nullable=True),
    sa.Column('golongan', sa.Enum('None', 'I/a', 'I/b', 'I/c', 'I/d', 'II/a', 'II/b', 'II/c', 'II/d', 'III/a', 'III/b', 'III/c', 'III/d', 'IV/a', 'IV/b', 'IV/c', 'IV/d', 'IV/e', name='golongan'), nullable=True),
    sa.Column('pendidikan_terakhir', sa.String(length=24), nullable=True),
    sa.Column('jenis_kelamin', sa.Enum('Laki-laki', 'Perempuan', name='gender'), nullable=True),
    sa.Column('tahun_masuk', sa.String(length=24), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_foto'),
    sa.UniqueConstraint('nama_foto_ijazah'),
    sa.UniqueConstraint('nik')
    )
    op.create_table('murid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_induk', sa.String(length=5), nullable=False),
    sa.Column('nama', sa.String(length=64), nullable=False),
    sa.Column('nama_panggilan', sa.String(length=24), nullable=False),
    sa.Column('anak_ke', sa.String(length=2), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('dusun', sa.String(length=24), nullable=True),
    sa.Column('kelurahan', sa.String(length=24), nullable=True),
    sa.Column('kecamatan', sa.String(length=24), nullable=True),
    sa.Column('kabupaten', sa.String(length=24), nullable=True),
    sa.Column('provinsi', sa.String(length=24), nullable=True),
    sa.Column('agama', sa.Enum('Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Kong Hu Cu', name='agama'), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=24), nullable=False),
    sa.Column('tanggal_lahir', sa.String(length=24), nullable=False),
    sa.Column('lulus', sa.Boolean(), nullable=True),
    sa.Column('nama_ibu_kandung', sa.String(length=64), nullable=False),
    sa.Column('jenis_kelamin', sa.Enum('Laki-laki', 'Perempuan', name='gender'), nullable=True),
    sa.Column('tahun_pelajaran', sa.String(length=24), nullable=True),
    sa.Column('foto_diri', sa.LargeBinary(length=4028), nullable=True),
    sa.Column('nama_foto_diri', sa.String(length=64), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_foto_diri'),
    sa.UniqueConstraint('nomor_induk')
    )
    op.create_table('nilai_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('aspek_penilaian', sa.Enum('Perkembangan Nilai Agama dan Moral', 'Perkembangan Sosial, Emosional', 'Perkembangan Bahasa', 'Perkembangan Kognitif', 'Perkembangan Fisik Motorik', 'Perkembangan Seni', name='aspek_penilaian'), nullable=False),
    sa.Column('semester', sa.Enum('Semester I', 'Semester II', name='semester'), nullable=False),
    sa.Column('tahun_pelajaran', sa.String(length=24), nullable=True),
    sa.Column('murid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['murid_id'], ['murid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wali_murid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=120), nullable=False),
    sa.Column('agama', sa.Enum('Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Kong Hu Cu', name='agama'), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('kelurahan', sa.String(length=60), nullable=True),
    sa.Column('kecamatan', sa.String(length=60), nullable=True),
    sa.Column('kabupaten', sa.String(length=60), nullable=True),
    sa.Column('provinsi', sa.String(length=60), nullable=True),
    sa.Column('jenis_kelamin', sa.Enum('Laki-laki', 'Perempuan', name='gender'), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=60), nullable=False),
    sa.Column('tanggal_lahir', sa.String(length=60), nullable=False),
    sa.Column('pekerjaan', sa.String(length=40), nullable=False),
    sa.Column('nomor_telepon', sa.String(length=12), nullable=False),
    sa.Column('murid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['murid_id'], ['murid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wali_murid')
    op.drop_table('nilai_model')
    op.drop_table('murid')
    op.drop_table('guru')
    op.drop_table('user')
    op.drop_table('jadwal_kelas')
    op.drop_index(op.f('ix_elearning_waktu_upload'), table_name='elearning')
    op.drop_table('elearning')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('profil_sekolah')
    op.drop_table('prestasi')
    op.drop_table('kelas')
    op.drop_index(op.f('ix_data_sekolah_waktu_upload'), table_name='data_sekolah')
    op.drop_table('data_sekolah')
    op.drop_index(op.f('ix_berita_waktu_upload'), table_name='berita')
    op.drop_table('berita')
    # ### end Alembic commands ###
